# Generated by Django 2.1.5 on 2019-01-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20190106_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalday',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.Goal', unique_for_date='created_at'),
        ),
    ]
