# Generated by Django 2.1.5 on 2019-01-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20190106_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='goalday',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='goalday',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
