# Generated by Django 2.1.5 on 2019-01-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20190106_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='goalday',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
