# Generated by Django 2.1.5 on 2019-01-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_auto_20190106_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalday',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='goalday',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='goals.Goal', unique_for_date='date'),
        ),
    ]
