# Generated by Django 2.1.5 on 2019-01-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_auto_20190106_1820'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goalday',
            unique_together={('created_at', 'goal')},
        ),
    ]
