# Generated by Django 2.1.5 on 2019-01-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_auto_20190106_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalday',
            name='date',
        ),
    ]
