# Generated by Django 2.1.5 on 2019-01-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_remove_goalday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='goalday',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
