# Generated by Django 2.1.5 on 2019-01-07 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_timesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesection',
            name='percent',
        ),
        migrations.AddField(
            model_name='timesection',
            name='hours',
            field=models.DecimalField(decimal_places=1, default=0.2, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesection',
            name='timepie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='goals.TimePie'),
        ),
    ]
