# Generated by Django 2.1.5 on 2019-01-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0015_auto_20190107_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='type_of',
            field=models.CharField(choices=[('HEALTH', 'HEALTH'), ('PROFESSIONAL', 'PROFESSIONAL'), ('PERSONAL', 'PERSONAL')], max_length=20, null=True),
        ),
    ]
