# Generated by Django 2.1.5 on 2019-01-22 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0017_auto_20190107_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(days=10), '10 Days'), (datetime.timedelta(days=30), '30 Days'), (datetime.timedelta(days=60), '60 Days'), (datetime.timedelta(days=90), '90 Days')], null=True),
        ),
    ]
